name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees: ['Braian-Quintian']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if a similar feature has already been requested.
      options:
        - label: I have searched the existing issues and none match my request
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: If applicable, show how the API would look.
      render: typescript
      placeholder: |
        // Example of how you'd like to use the feature
        versioningMiddleware(handlers, {
          newOption: 'value',
        });

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: importance
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Important for my use case
        - Critical / Blocking
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Are you willing to contribute?
      description: Would you be willing to submit a PR for this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature
